In [68]:
import pandas as pd 
medsynth= pd.read_csv('/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/data/output/notes_dial_pairs/phase_2_to_12_combined/total_data_with_counts.csv', sep="|")

medsynth.head(25)

,Unnamed: 0.1,Unnamed: 0,Disease Description,Scenario,Note,Polished Note,Abbreviated Note,Role,dial,polished_dial,src_len_with_speakers,src_len_without_speakers,src_turnlen,note_len,note_sentlen,avg_tokens_per_sentence
0,0,0,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n1) Medical Outc...,**1. Subjective:**\n\n **Chief Complaint (CC...,**1. Subjective:** **Chief Complaint (CC):...,**1. Subjective:**\n\n **CC:**\n - L knee ...,Orthopedic Specialist,**Doctor:** Hello! It’s good to see you today....,[doctor]: Hello! It’s good to see you today. H...,1248,1033,54,447,20,22.350000
1,1,1,PAIN IN LEFT KNEE,ROLE: General Physician\n\n- **Medical Outcome...,**1. Subjective:**\n\n - **Chief Complaint (...,**1. Subjective:** - **Chief Complaint (CC...,**1. Subjective:**\n\n - **CC:** Pain in L k...,General Physician,**CHIEF COMPLAINT**\n\nPain in left knee.\n\n*...,"[doctor] Hi there, how are you today? [patien...",1216,1216,77,597,21,28.428571
2,2,2,PAIN IN LEFT KNEE,ROLE: Family Medicine Physician \n\n** 1) Medi...,#####\n**1. Subjective:**\n\n**Chief Complaint...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\nSevere R hip pa...,Family Medicine Physician,"[doctor] Good morning, how are you doing today...","[doctor] Good morning, how are you doing today...",1100,1100,50,665,25,26.600000
3,3,3,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n**Scenario:**\n...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:** \nModerate knee...,Orthopedic Specialist,[doctor] Good morning! How are you feeling tod...,[doctor] Good morning! How are you feeling tod...,1166,1166,57,657,26,25.269231
4,4,4,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n** Medical Outc...,#####\n**1. Subjective:**\n\n**Chief Complaint...,##### **1. Subjective:** **Chief Complaint (C...,#####\n**1. Subjective:**\n\n**CC:** \nModera...,Orthopedic Specialist,"[doctor]: Hello Mr. Doe, how are you doing tod...","[doctor]: Hello Mr. Doe, how are you doing tod...",1053,866,47,670,18,37.222222
5,5,5,"URINARY TRACT INFECTION, SITE NOT SPECIFIED",**ROLE:** Family Medicine Physician\n\n**1) Me...,#####\n\n**1. Subjective:**\n\n**Chief Complai...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\n- Pt presents w...,Role not found in the first 5 lines.,"```markdown\n[doctor] Hi there, how are you to...","```markdown [doctor] Hi there, how are you tod...",897,897,42,652,20,32.600000
6,6,6,"URINARY TRACT INFECTION, SITE NOT SPECIFIED",**ROLE:** Family Medicine Physician\n\n**AGE:*...,#### EMERGENCY VISIT MEDICAL NOTE\n\n**1. Subj...,#### EMERGENCY VISIT MEDICAL NOTE **1. Subjec...,#### EMERGENCY VISIT MEDICAL NOTE\n\n**1. Subj...,Role not found in the first 5 lines.,**Doctor:** Good afternoon. How are you feelin...,[doctor]: Good afternoon. How are you feeling ...,1139,948,48,705,17,41.470588
7,7,7,"URINARY TRACT INFECTION, SITE NOT SPECIFIED",**ROLE:** Family Medicine Physician\n\n**Scena...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\nFrequent urinat...,Role not found in the first 5 lines.,**Doctor:** Good morning! How are you doing to...,[doctor]: Good morning! How are you doing toda...,793,650,36,556,20,27.800000
8,8,8,"URINARY TRACT INFECTION, SITE NOT SPECIFIED",ROLE: Family Medicine Physician\n\n1) Medical ...,#####\n1. Subjective:\n **Chief Complaint (C...,##### 1. Subjective: **Chief Complaint (CC)...,"#####\n1. Subjective:\n **CC:** \n Pt, Emi...",Family Medicine Physician,"```plaintext\n[doctor] Hi there, how are you d...","```plaintext [doctor] Hi there, how are you do...",816,816,39,504,18,28.000000
9,9,9,"URINARY TRACT INFECTION, SITE NOT SPECIFIED",ROLE: Family Medicine Physician\n\n**Scenario ...,#####\n**1. Subjective:**\n\n**Chief Complaint...,##### **1. Subjective:** **Chief Complaint (C...,#####\n**1. Subjective:**\n\n**CC:**\n45 y/o F...,Family Medicine Physician,"**Doctor**: Good morning, how are you doing to...","[doctor]: Good morning, how are you doing toda...",1045,870,44,534,17,31.411765
10,10,10,OTHER GENERAL SYMPTOMS AND SIGNS,ROLE: General Physician\n\n** Scenario Variabl...,### Medical Note\n\n#### 1. Subjective:\n\n**C...,### Medical Note #### 1. Subjective: **Chief...,### Medical Note\n\n#### 1. Subjective:\n\n**C...,General Physician,"```plaintext\n[doctor] Hi Mr. Cortez, how are ...","```plaintext [doctor] Hi Mr. Cortez, how are y...",1187,1187,53,745,31,24.032258
11,11,11,OTHER GENERAL SYMPTOMS AND SIGNS,ROLE: General Physician\n\n**Scenario:**\n\n**...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:** \nPersistent dry...,General Physician,"[doctor] Hi there, how are you doing today?\n\...","[doctor] Hi there, how are you doing today? [...",1012,1012,47,710,23,30.869565
12,12,12,OTHER GENERAL SYMPTOMS AND SIGNS,ROLE: General Physician\n\n**Scenario:**\n\n**...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:** \n- Persistent m...,General Physician,"**Doctor:** Good morning, Ms. Johnson. How are...","[doctor]: Good morning, Ms. Johnson. How are y...",995,832,41,632,24,26.333333
13,13,13,OTHER GENERAL SYMPTOMS AND SIGNS,ROLE: General Physician\n\n1) Medical Outcome:...,#####\n1. **Subjective:**\n\n **Chief Compl...,1. **Subjective:** **Chief Complaint (CC)...,1. **Subjective:**\n\n **CC:**\n - Fatig...,General Physician,"```\n[doctor] Hello there, I see you’ve been h...","[doctor]: Hello there, I see you’ve been havin...",1142,959,46,577,28,20.607143
14,14,14,OTHER GENERAL SYMPTOMS AND SIGNS,ROLE: General Physician\n\n- Medical Outcome: ...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\nPersistent coug...,General Physician,"**Doctor:** Hi, good morning. How are you doin...","[doctor]: Hi, good morning. How are you doing ...",1143,952,48,682,26,26.230769
15,15,15,"NAUSEA WITH VOMITING, UNSPECIFIED",ROLE: General Physician\n\nDemographic Informa...,#####\n**1. Subjective:**\n\n**Chief Complaint...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:** \nN/V\n\n**HPI:*...,General Physician,"```\n[doctor] Hi there, how are you doing toda...","[doctor]: Hi there, how are you doing today? ...",1065,882,46,582,24,24.250000
16,16,16,"NAUSEA WITH VOMITING, UNSPECIFIED",ROLE: Family Medicine Physician\n\n**Scenario:...,#####\n**1. Subjective**\n\n**Chief Complaint ...,##### **1. Subjective** **Chief Complaint (CC...,#####\n**1. Subjective**\n\n**CC:**\nSevere N/...,Family Medicine Physician,"```plaintext\n[doctor] Good morning, how are y...","```plaintext [doctor] Good morning, how are yo...",854,854,31,588,21,28.000000
17,17,17,"NAUSEA WITH VOMITING, UNSPECIFIED",ROLE: Family Medicine Physician\n\nDemographic...,#####\n**1. Subjective:**\n\n**Chief Complaint...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\n- N/V\n\n**HPI:...,Family Medicine Physician,"[doctor] Hi, how are you doing today?\n[patien...","[doctor] Hi, how are you doing today? [patient...",1057,1057,64,552,21,26.285714
18,18,18,"NAUSEA WITH VOMITING, UNSPECIFIED",ROLE: General Physician\n\n1) Medical Outcome:...,#####\n**1. Subjective:**\n\n**Chief Complaint...,##### **1. Subjective:** **Chief Complaint (C...,#####\n**1. Subjective:**\n\n**CC:**\nNausea w...,General Physician,"[doctor] Good morning, Ms. Zhang. How are you ...","[doctor] Good morning, Ms. Zhang. How are you ...",742,742,32,515,20,25.750000
19,19,19,"NAUSEA WITH VOMITING, UNSPECIFIED",ROLE: Family Medicine Physician\n\nDEMOGRAPHIC...,#####\n**1. Subjective:**\n\n**Chief Complaint...,##### **1. Subjective:** **Chief Complaint (C...,#####\n**1. Subjective:**\n\n**CC:** \nN/V\n\...,Family Medicine Physician,"[doctor] Hello Maria, how are you doing today?...","[doctor] Hello Maria, how are you doing today?...",1432,1432,60,586,26,22.538462
20,20,20,LOW BACK PAIN,**ROLE:** Family Medicine Physician\n\n1) **Me...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\nLower back pain...,Role not found in the first 5 lines.,"[doctor] Hello, how are you doing today?\n\n[p...","[doctor] Hello, how are you doing today? [pat...",1132,1132,54,664,29,22.896552
21,21,21,LOW BACK PAIN,**ROLE:** Orthopedic Specialist\n\n**SCENARIO ...,#####\n**1. Subjective:**\n\n**Chief Complaint...,##### **1. Subjective:** **Chief Complaint (C...,#####\n**1. Subjective:**\n\n**CC:**\nSevere L...,Role not found in the first 5 lines.,**Conversation Transcript:**\n\n**Doctor:** Hi...,"[doctor]: Hi Mr. Jones, how are you feeling to...",973,786,47,613,26,23.576923
22,22,22,LOW BACK PAIN,**ROLE:** Family Medicine Physician\n\n**Scena...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:** **Chief Complaint (CC):** ...,"**1. Subjective:**\n\n**CC:** \nSharp, shooti...",Role not found in the first 5 lines.,"**Chief Complaint**\n\n**Doctor:** Hi there, I...","[doctor]: Hi there, I see you're back for a fo...",1266,1039,57,633,20,31.650000
23,23,23,LOW BACK PAIN,**ROLE:** Family Medicine Physician\n\n**1) Me...,#####\n**1. Subjective:**\n\n**Chief Complaint...,##### **1. Subjective:** **Chief Complaint (C...,#####\n**1. Subjective:**\n\n**CC:**\nLower ba...,Role not found in the first 5 lines.,"**Doctor**: Good morning, how are you doing to...","[doctor]: Good morning, how are you doing toda...",1078,899,47,657,16,41.062500
24,24,24,LOW BACK PAIN,**ROLE:** Family Medicine Physician\n\n**SCENA...,#####\n**1. Subjective:**\n\n**Chief Complaint...,**1. Subjective:** **Chief Complaint (CC):** ...,**1. Subjective:**\n\n**CC:**\n- Low back pain...,Role not found in the first 5 lines.,"[doctor] Good morning, how are you today?\n\n[...","[doctor] Good morning, how are you today? [pa...",957,957,44,532,19,28.000000

In [67]:
print(medsynth["Polished Note"][7000])

##### **1. Subjective:**  **Chief Complaint (CC):** Moderate wheezing and shortness of breath.  **History of Present Illness (HPI):** The patient, Maria Gonzalez, is a 35-year-old Hispanic female with a known history of asthma who presents with worsening symptoms over the past three days. She reports moderate wheezing, shortness of breath, chest tightness, and occasional coughing. Symptoms are exacerbated at night and with physical exertion, significantly impacting her daily activities and sleep.  **Review of Systems (ROS):** - **Constitutional:** Reports interrupted sleep averaging 5-6 hours per night due to asthma symptoms. - **Respiratory:** Positive for wheezing, shortness of breath, chest tightness, and occasional coughing. - **Cardiovascular:** Denies chest pain or palpitations. - **Gastrointestinal:** Denies nausea, vomiting, or changes in bowel habits. - **Musculoskeletal:** Denies joint pain or swelling. - **Neurological:** Denies headaches, dizziness, or syncope.  **2. Objective:**  **Vital Signs:** - Temperature: 98.6°F - Pulse: 88 bpm - Respiratory Rate: 22 breaths per minute - Blood Pressure: 120/80 mmHg - Pulse Oxygenation: 95% on room air  **Physical Examination:** - **General:** Patient appears in moderate respiratory distress, no cyanosis. - **Respiratory:** Bilateral wheezing on auscultation, decreased breath sounds in the lower lobes. - **Cardiovascular:** Regular rate and rhythm; no murmurs, gallops, or rubs. - **Abdomen:** Soft, non-tender, no hepatosplenomegaly. - **Extremities:** No clubbing, cyanosis, or edema.  **3. Assessment:**  **Primary Diagnosis:** Mild persistent asthma with (acute) exacerbation.  **Differential Diagnoses:** - Chronic obstructive pulmonary disease (COPD) - Respiratory tract infection - Cardiac-related dyspnea  **4. Plan:**  **Medical Treatment:** - **Albuterol Inhaler 90 mcg:** 2 puffs every 4-6 hours as needed for wheezing or shortness of breath. - **Fluticasone Propionate Inhaler 110 mcg:** 2 puffs twice daily.  **Follow-up and Referrals:** - Schedule follow-up appointment in 2 weeks. - Referral to Pulmonologist, Dr. Amanda Smith, for further asthma management.  **Investigations:** - Spirometry to evaluate lung function. - Complete Blood Count (CBC) and Allergy Panel to evaluate potential allergens and eosinophilia.  **Lifestyle and Patient Education:** - Encourage avoidance of known allergens. - Emphasize the importance of regular medication adherence. - Discuss and implement an asthma action plan. - Instruct on proper inhaler technique.  **Patient Agreements:** The patient understands and agrees with the recommended medical treatment plan and follow-up. She is highly cooperative and adherent to medical advice.

We need to add sentence counts for the dial:

In [12]:
import spacy

nlp = spacy.load("en_core_sci_lg")

/Users/ahmadrezaie/miniforge3/lib/python3.10/site-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [13]:
import re


# Function to calculate the required metrics and add them to the row
def add_sentence_len_to_dial(row):
    # Original dialogue with speaker tokens
    original_dialogue = row['polished_dial']
    # Remove speaker tokens from the dialogue
    dialogue_without_speakers = len( re.findall( r"\[\S+\]", row['dialogue'] ) ) #re.sub(r"\[\S+\]:", "", original_dialogue)
    doc_dial = nlp(dialogue_without_speakers)

    # Calculate the number of sentences in the note using SpaCy's sentence detection
    sentences = list(doc_dial.sents)
    row['dial_sentlen'] = len(sentences)

    return row

In [14]:
from tqdm import tqdm


# Integrate tqdm with pandas
tqdm.pandas()

# Apply the add_lengths function with a progress bar
medsynth = medsynth.progress_apply(add_sentence_len_to_dial, axis=1)

NameError: name 'medsynth' is not defined

### Calculate stats for Aci-Bench

#### Valid only to get the ratoio:

In [18]:


import pandas as pd
aci_valid= pd.read_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/code/aci_challenge_data/valid.csv")
from tqdm import tqdm
import re

# Integrate tqdm with pandas
tqdm.pandas()
aci_valid.head()

,dataset,encounter_id,dialogue,note
0,virtassist,D2N068,"[doctor] hi , brian . how are you ?\n[patient]...",CHIEF COMPLAINT\n\nFollow-up of chronic proble...
1,virtassist,D2N069,"[doctor] hi , ms. thompson . i'm dr. moore . h...",CC:\n\nRight knee pain.\n\nHPI:\n\nMs. Thompso...
2,virtassist,D2N070,[doctor] hi logan . how are you ?\n[patient] h...,CHIEF COMPLAINT\n\nBack pain.\n\nHISTORY OF PR...
3,virtassist,D2N071,[doctor] i know the nurse told you about dax ....,CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...
4,virtassist,D2N072,"[doctor] hi , ms. brooks . i'm dr. baker . how...",CC:\n\nRight finger pain.\n\nHPI:\n\nMs. Brook...

In [19]:

# Function to calculate the required metrics and add them to the row
def add_lengths(row):
    # Original dialogue with speaker tokens
    original_dialogue = row['dialogue']

    # Remove speaker tokens from the dialogue
    dialogue_without_speakers = re.sub(r"\[\S+\]:", "", original_dialogue)

    # Tokenize the original dialogue (including speaker tokens) using SpaCy
    #doc_with_speakers = nlp(original_dialogue)
    row['src_len_with_speakers'] = len( row['dialogue'].split() ) #len(doc_with_speakers)

    # Tokenize the dialogue (excluding speaker tokens) using SpaCy
    #doc_without_speakers = nlp(dialogue_without_speakers)
    row['src_len_without_speakers'] = len(dialogue_without_speakers.split())

    # Calculate the number of turns in the dialogue (number of times [doctor]: or [patient]: appears)
    row['src_turnlen'] = len( re.findall( r"\[\S+\]", row['dialogue'] ) )
    #row['src_turnlen'] = len(re.findall(r"\[\S+\]", row['dialogue']))

    # Tokenize the note and calculate the number of tokens
    doc_note =  nlp( row['note'] )
    row['note_len'] = len(doc_note)

    # Calculate the number of sentences in the note using SpaCy's sentence detection
    
    row['note_sentlen'] = len( list( doc_note.sents ) )

    doc_dial = nlp(dialogue_without_speakers)

    # Calculate the number of sentences in the note using SpaCy's sentence detection
    sentences = list(doc_dial.sents)
    row['dial_sentlen'] = len(sentences)

    return row

In [20]:
# Apply the add_lengths function with a progress bar
aci_valid = aci_valid.progress_apply(add_lengths, axis=1)

100%|██████████| 20/20 [00:08<00:00,  2.40it/s]

In [21]:
# After fix: 

df = aci_valid
avg_turns = df['src_turnlen'].mean()
avg_dial_tokens_with_speakers = df['src_len_with_speakers'].mean()
avg_dial_tokens_without_speakers = df['src_len_without_speakers'].mean()
avg_note_tokens = df['note_len'].mean()
avg_note_sentences = df['note_sentlen'].mean()
avg_diale_sentences= df['dial_sentlen'].mean()


# Print the results
print("Average Number of Turns in Dialogue:", avg_turns)
print("Average Number of Tokens in Dialogue (with speaker tokens):", avg_dial_tokens_with_speakers)
print("Average Number of Tokens in Dialogue (without speaker tokens):", avg_dial_tokens_without_speakers)
print("avg_diale_sentences: ", avg_diale_sentences)
print("Average Number of Tokens in Notes:", avg_note_tokens)
print("Average Number of Sentences in Notes:", avg_note_sentences)

Average Number of Turns in Dialogue: 52.55
Average Number of Tokens in Dialogue (with speaker tokens): 1221.45
Average Number of Tokens in Dialogue (without speaker tokens): 1221.45
avg_diale_sentences:  19.5
Average Number of Tokens in Notes: 522.7
Average Number of Sentences in Notes: 35.65

So, the ratio would be: 49/35.65= 1.37

#### Aci whole:

In [22]:
import pandas as pd
aci_whole= pd.read_csv("/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/data/input/aci_data_all_together.csv")
from tqdm import tqdm
import re

# Integrate tqdm with pandas
tqdm.pandas()
aci_whole.head()

,filename,dataset,encounter_id,dialogue,note,id,doctor_name,patient_gender,patient_age,patient_firstname,patient_familyname,cc,2nd_complaints
0,clef_taskC_test3,virtassist,D2N168,"[doctor] hi diane , how are you ?\n[patient] i...",CHIEF COMPLAINT\n\nEmergency room follow-up.\n...,VA013,NaN,female,28.0,Diane,Baker,ER follow-up,type 2 diabetes;depression;hypertension
1,clef_taskC_test3,virtassist,D2N169,"[doctor] hi alan , how are you ?\n[patient] hi...",CHIEF COMPLAINT\n\nShortness of breath.\n\nHIS...,VA039,NaN,male,61.0,Alan,Butler,shortness of breath,migraines;reflux;hx cataract surgery
2,clef_taskC_test3,virtassist,D2N170,"[doctor] hi joyce , how are you ?\n[patient] i...",CHIEF COMPLAINT\n\nFollow-up to an abnormal la...,VA009,NaN,female,50.0,Joyce,Price,abnormal lab finding,COPD;congestive heart failure
3,clef_taskC_test3,virtassist,D2N171,"[doctor] hi evelyn , how are you ?\n[patient] ...",CHIEF COMPLAINT\n\nAnnual exam.\n\nHISTORY OF ...,VA008,NaN,female,56.0,Evelyn,Morris,annual exam,coronary artery disease;hx carpal tunnel relea...
4,clef_taskC_test3,virtassist,D2N172,"[doctor] morning roy , how are you doing ?\n[p...",CHIEF COMPLAINT\n\nHistory of depression.\n\nH...,VA006,NaN,male,50.0,Roy,Sanchez,abnormal labs,hypertension;depression

In [23]:
# Apply the add_lengths function with a progress bar
aci_whole = aci_whole.progress_apply(add_lengths, axis=1)

100%|██████████| 207/207 [01:29<00:00,  2.30it/s]

In [24]:
# After fix: 

df = aci_whole
avg_turns = df['src_turnlen'].mean()
avg_dial_tokens_with_speakers = df['src_len_with_speakers'].mean()
avg_dial_tokens_without_speakers = df['src_len_without_speakers'].mean()
avg_note_tokens = df['note_len'].mean()
avg_note_sentences = df['note_sentlen'].mean()
avg_diale_sentences= df['dial_sentlen'].mean()


# Print the results
print("Average Number of Turns in Dialogue:", avg_turns)
print("Average Number of Tokens in Dialogue (with speaker tokens):", avg_dial_tokens_with_speakers)
print("Average Number of Tokens in Dialogue (without speaker tokens):", avg_dial_tokens_without_speakers)
print("avg_diale_sentences: ", avg_diale_sentences)
print("Average Number of Tokens in Notes:", avg_note_tokens)
print("Average Number of Sentences in Notes:", avg_note_sentences)

Average Number of Turns in Dialogue: 55.24154589371981
Average Number of Tokens in Dialogue (with speaker tokens): 1302.0434782608695
Average Number of Tokens in Dialogue (without speaker tokens): 1302.0434782608695
avg_diale_sentences:  19.463768115942027
Average Number of Tokens in Notes: 521.2608695652174
Average Number of Sentences in Notes: 36.6231884057971

So:

* Average Number of Sentences in Notes= 50
* avg_diale_sentences= 27

### MedSynth: re-run

In [25]:
medsynth= pd.read_csv('/Users/ahmadrezaie/2_My_papers/Synthetic_Data_Gen/data/output/notes_dial_pairs/phase_2_to_12_combined/total_data.csv', sep="|")
medsynth

,Unnamed: 0,Disease Description,Scenario,Note,Polished Note,Abbreviated Note,Role,dial,polished_dial
0,0,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n1) Medical Outc...,**1. Subjective:**\n\n **Chief Complaint (CC...,**1. Subjective:**\n\n **Chief Complaint (CC...,**1. Subjective:**\n\n **CC:**\n - L knee ...,Orthopedic Specialist,**Doctor:** Hello! It’s good to see you today....,[doctor]: Hello! It’s good to see you today. H...
1,1,PAIN IN LEFT KNEE,ROLE: General Physician\n\n- **Medical Outcome...,**1. Subjective:**\n\n - **Chief Complaint (...,**1. Subjective:**\n\n - **Chief Complaint (...,**1. Subjective:**\n\n - **CC:** Pain in L k...,General Physician,**CHIEF COMPLAINT**\n\nPain in left knee.\n\n*...,"[doctor] Hi there, how are you today?\n\n[pati..."
2,2,PAIN IN LEFT KNEE,ROLE: Family Medicine Physician \n\n** 1) Medi...,#####\n**1. Subjective:**\n\n**Chief Complaint...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**CC:**\nSevere R hip pa...,Family Medicine Physician,"[doctor] Good morning, how are you doing today...","[doctor] Good morning, how are you doing today..."
3,3,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n**Scenario:**\n...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**CC:** \nModerate knee...,Orthopedic Specialist,[doctor] Good morning! How are you feeling tod...,[doctor] Good morning! How are you feeling tod...
4,4,PAIN IN LEFT KNEE,ROLE: Orthopedic Specialist\n\n** Medical Outc...,#####\n**1. Subjective:**\n\n**Chief Complaint...,#####\n**1. Subjective:**\n\n**Chief Complaint...,#####\n**1. Subjective:**\n\n**CC:** \nModera...,Orthopedic Specialist,"[doctor]: Hello Mr. Doe, how are you doing tod...","[doctor]: Hello Mr. Doe, how are you doing tod..."
...,...,...,...,...,...,...,...,...,...
10030,40,CANDIDAL ESOPHAGITIS,ROLE: Gastroenterologist\n\n** 1) Medical Outc...,#####\n**1. Subjective:**\n \n**Chief Compla...,#####\n**1. Subjective:**\n \n**Chief Compla...,#####\n**1. Subjective:**\n \n**CC:**\nDiffi...,Gastroenterologist,"**Patient**: Good morning, doctor.\n\n**Doctor...",[doctor]: Good morning. How are you doing toda...
10031,41,CANDIDAL ESOPHAGITIS,ROLE: Gastroenterologist\n\n**1) Medical Outco...,### Gastroenterologist Medical Note\n\n#### 1....,### Gastroenterologist Medical Note\n\n#### 1....,### Gastroenterologist Medical Note\n\n#### 1....,Gastroenterologist,"**Doctor:** Hi there, how are you doing today?...","**Doctor:** Hi there, how are you doing today?..."
10032,42,CANDIDAL ESOPHAGITIS,ROLE: Gastroenterologist\n\n**Scenario:**\n\n*...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,**1. Subjective:**\n\n**CC:**\nDysphagia and C...,Gastroenterologist,"**Doctor:** Hi Mr. Harris, how are you doing t...","[doctor]: Hi Mr. Harris, how are you doing tod..."
10033,43,CANDIDAL ESOPHAGITIS,**ROLE:** Gastroenterologist\n\n**Scenario:**\...,#####\n**1. Subjective:**\n**Chief Complaint (...,#####\n**1. Subjective:**\n**Chief Complaint (...,#####\n**1. Subjective:**\n**CC:** \nSevere pa...,Role not found in the first 5 lines.,"**Conversation:**\n\n**Doctor:** Good morning,...","[doctor]: Good morning, Ms. Lee. How are you d..."
10034,44,CANDIDAL ESOPHAGITIS,ROLE: Gastroenterologist\n\n**Scenario:**\n\n1...,#####\n\n**1. Subjective:**\n\n**Chief Complai...,**1. Subjective:**\n\n**Chief Complaint (CC):*...,"**1. Subjective:**\n\n**CC:**\nThe pt, a 55 y/...",Gastroenterologist,**Dialogue:**\n\n---\n\n**Doctor:** Good morni...,[doctor]: Good morning. How are you doing toda...

In [ ]:

# Function to calculate the required metrics and add them to the row
def add_lengths_medsynth(row):
    # Original dialogue with speaker tokens
    original_dialogue = row['polished_dial']

    # Remove speaker tokens from the dialogue
    dialogue_without_speakers = re.sub(r"\[\S+\]:", "", original_dialogue)

    # Tokenize the original dialogue (including speaker tokens) using SpaCy
    #doc_with_speakers = nlp(original_dialogue)
    row['src_len_with_speakers'] = len( row['polished_dial'].split() ) #len(doc_with_speakers)

    # Tokenize the dialogue (excluding speaker tokens) using SpaCy
    #doc_without_speakers = nlp(dialogue_without_speakers)
    row['src_len_without_speakers'] = len(dialogue_without_speakers.split())

    # Calculate the number of turns in the dialogue (number of times [doctor]: or [patient]: appears)
    row['src_turnlen'] = len( re.findall( r"\[\S+\]", row['polished_dial'] ) )
    #row['src_turnlen'] = len(re.findall(r"\[\S+\]", row['dialogue']))

    # Tokenize the note and calculate the number of tokens
    doc_note =  nlp( row['Polished Note'] )
    row['note_len'] = len(doc_note)

    # Calculate the number of sentences in the note using SpaCy's sentence detection
    
    row['note_sentlen'] = len( list( doc_note.sents ) )

    doc_dial = nlp(dialogue_without_speakers)

    # Calculate the number of sentences in the note using SpaCy's sentence detection
    sentences = list(doc_dial.sents)
    row['dial_sentlen'] = len(sentences)

    return row